# These are supported funding model platforms

# GitHub Sponsors (up to 4 usernames)
github: [lachlanchen]

# External platforms (fill in if/when you use them)
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 

# Custom links (up to 4)
custom: [
  "https://github.com/sponsors/lachlanchen",
  "https://lazying.art",
  "https://chat.lazying.art",
  "https://onlyideas.art"
]
